name: Release
on:
#  schedule:
#    - cron: '*/15 * * * *'
  push:
    branches:
      - main

jobs:
  date:
    name: Date
    runs-on: ubuntu-latest
    steps:
      - name: Get current week number
        run: echo "MODWEEK=$(( `date +%V` % 3 ))" >> $GITHUB_ENV
    outputs:
      modweek: ${{ env.MODWEEK }}

  release:
    name: Release
    needs: date
    if: needs.date.outputs.modweek == '0'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      #- name: Install dependencies
      #  run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm install @semantic-release/exec -D
          npx semantic-release
